### ISSUE TITLE
ListView is not drugging down

### ISSUE THREAD

**Issue by DanilKurkin** [jamesmontemagno/Xamarin.Forms-Awesome-Controls#1]
After updating XF to 1.3.1 Pull to refresh behavior is strange - I do have an icon of refreshing when pulling the list, but list itself is not pulled and staying still as it is (instead of moving down following the motion).

 List get updated and all works fine apart from that.

**Comment by jamesmontemagno** [comment]
In Android or iOS?

**Comment by DanilKurkin** [comment]
Hi, Sorry didn't mention platform - Android.
On iOS is all fine

**Comment by jamesmontemagno** [comment]
It is not supposed to drag down, as that is not how the control works with the latest versions from Google. You would have to use a different pull to refresh control.
