### ISSUE TITLE
Packages are mising

### ISSUE THREAD

**Issue by Sudhacc** [jamesmontemagno/Xamarin.Forms-Awesome-Controls#11]
All the packages that are missing in the project. able to add the packages but not able to find Refactored.GifImageView. Please check with this and update

**Comment by jamesmontemagno** [comment]
Did you restore the nuget packages? https://www.nuget.org/packages/Refractored.GifImageView/

**Comment by Sudhacc** [comment]
Yes i did restore the packages, and needed to solve some runtime exceptions. it is working now. thankyou for the reply

**Comment by Sudhacc** [comment]
Hi James,

Is there a way to display Gif image from device storage, instead of giving URI. I have tried to do that but all i have achieved is to display static image without animation(the downloaded image is animating in the device gallery). Please advice me on this.

Regards,
Sudha
