### ISSUE TITLE
PullToRefreshLayout support for WinRT / Windows 10 apps

### ISSUE THREAD

**Issue by dominik-weber** [jamesmontemagno/Xamarin.Forms-Awesome-Controls#12]
Do you have any plans to support pull to refresh for Windows 10 (UWP) apps?

**Comment by jamesmontemagno** [comment]
Nope, I do not plan to add this support at all. I don't think pull to refresh exists out of the box with UWP, let me know if it does and I could look into it. Only UWP though.
