### ISSUE TITLE
Setting IsPullToRefreshEnabled to false does not work on iOS

### ISSUE THREAD

**Issue by IanDuncanson** [jamesmontemagno/Xamarin.Forms-Awesome-Controls#14]
If you set IsPullToRefreshEnabled it doesn't seem to do anything. Quite possibly related to the following question on SO - http://stackoverflow.com/questions/19480424/how-do-i-hide-a-uirefreshcontrol

To disable, you need to fully remove the UIRefresh control, not simply set Enabled to false.

**Comment by jamesmontemagno** [comment]
Moving to: https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout
