### ISSUE TITLE
Application crashes, pullToRefresh component is a reason

### ISSUE THREAD

**Issue by DmitriySmirnov** [jamesmontemagno/Xamarin.Forms-Awesome-Controls#15]
In logs I see the following error:

Message: [ArgumentException: 'jobject' must not be IntPtr.Zero. Parameter name: jobject]
 Android.Runtime.JNIEnv.CallNonvirtualBooleanMethod(IntPtr jobject, IntPtr jclass, IntPtr jmethod):0
 Android.Support.V4.Widget.SwipeRefreshLayout.get_Refreshing():0
 Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer.set_Refreshing(Boolean value):0
 Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer.UpdateIsRefreshing():0
 Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer.HandlePropertyChanged(System.Object sender, System.ComponentModel.PropertyChangedEventArgs e):0
    (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
 Xamarin.Forms.BindableObject.OnPropertyChanged(System.String propertyName):0
 Xamarin.Forms.BindableObject.SetValueActual(Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindablePropertyContext context, System.Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent):0
 Xamarin.Forms.BindableObject.SetValueCore(Xamarin.Forms.BindableProperty property, System.Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes):0
 Xamarin.Forms.BindingExpression.ApplyCore(System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, Boolean fromTarget):0
 Xamarin.Forms.BindingExpression.Apply(Boolean fromTarget):0
 Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__38_0():0
 Java.Lang.Thread+RunnableImplementor.Run():0
 Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this):0
    (wrapper dynamic-method) System.Object:bf030382-1fa2-4dc6-894b-ec49ce37e172 (intptr,intptr)
    --- End of stack trace from previous location where exception was thrown ---
 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():0
 Android.Runtime.JNIEnv.CallVoidMethod(IntPtr jobject, IntPtr jmethod, Android.Runtime.JValue\* parms):0
 Android.App.Activity.RunOnUiThread(IRunnable action):0
 Android.App.Activity.RunOnUiThread(System.Action action):0
 Xamarin.Forms.Forms+AndroidPlatformServices.BeginInvokeOnMainThread(System.Action action):0
 Xamarin.Forms.Device.BeginInvokeOnMainThread(System.Action action):0
 Xamarin.Forms.BindingExpression+BindingExpressionPart.PropertyChanged(System.Object sender, System.ComponentModel.PropertyChangedEventArgs args):0
    (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
 WildApricot.MobileBackend.Logic.ViewModelBase.FirePropertyChanged(System.String propertyName):0
 WildApricot.MobileBackend.Logic.ViewModelBase.SetValue[T](WildApricot.MobileBackend.Logic.T value, System.String propertyName):0
 WildApricot.MobileBackend.Logic.ViewModelBase.set_IsDataLoading(Boolean value):0
 WildApricot.MobileBackend.Logic.ContactDetailsScreenViewModel+<ReloadData>d__2a.MoveNext():0
    --- End of stack trace from previous location where exception was thrown ---
 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():0
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task):0
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task):0
 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task task):0
 System.Runtime.CompilerServices.TaskAwaiter.GetResult():0
 WildApricot.MobileBackend.Logic.ViewModelBase+<StartReloadData>d__3.MoveNext():0
    --- End of stack trace from previous location where exception was thrown ---
 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():0
 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0(System.Object state):0
 Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0():0
 Java.Lang.Thread+RunnableImplementor.Run():0
 Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this):0
    (wrapper dynamic-method) System.Object:bf030382-1fa2-4dc6-894b-ec49ce37e172 (intptr,intptr)

**Comment by jamesmontemagno** [comment]
What version of forms and of the pull to refresh are you using? Can you just bring the library into your project and test it? I am using it currently with 2.1.0-pre2 with no issues.

**Comment by jamesmontemagno** [comment]
Fixed in latest nuget update in about 10 minutes

**Comment by jamesmontemagno** [comment]
All further discussion is here: https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout

**Comment by DmitriySmirnov** [comment]
Hi James.
Did you publish code changes on github? I don't see new commits here.

С уважением, Смирнов Дмитрий.

2016-02-10 5:59 GMT+03:00 James Montemagno notifications@github.com:

**Comment by jamesmontemagno** [comment]
Yes, like I posted I moved the code months ago to another repo and already
pushed a new nuget

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout

**Comment by SlavaChernikoff** [comment]
Hi James.

We still see a lot of crashes in our Xamarin Insights. Could you please help us.

Stacktrace:

System.ObjectDisposedExceptionCannot access a disposed object. Object name: 'Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer'.
Raw
Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self)
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(string encodedMember, IJavaPeerable self, JniArgumentValue\* parameters)
Android.Views.View.set_Alpha(float value)
Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateOpacity()
Xamarin.Forms.Platform.Android.VisualElementTracker.HandlePropertyChanged(object sender, PropertyChangedEventArgs e)
Xamarin.Forms.Platform.Android.VisualElementTracker.HandleRedrawNeeded(object sender, EventArg<_> e)
System.EventHandler<EventArg<VisualElement>>.invoke_void_object_TEventArgs(object, EventArg<VisualElement>)(wrapper delegate-invoke)
Xamarin.Forms.VisualElement.BatchCommit()
Xamarin.Forms.AnimationExtensions.HandleTweenerUpdated(object o, EventArgs args)
Xamarin.Forms.Tweener.<Start>b__26_0(long step)
Xamarin.Forms.Ticker.SendSignals(int timestep)
at Xamarin.Forms.Platform.Android.AndroidTicker.<.ctor>b__1_0 (System.Object sender, Android.Animation.AnimatorUpdateEventArgs e) <0x65593b18 + 0x0001f> in <filename unknown>:0
Android.Animation.ValueAnimator.IAnimatorUpdateListenerImplementor.OnAnimationUpdate(ValueAnimator animation)
Android.Animation.ValueAnimator.IAnimatorUpdateListenerInvoker.n_OnAnimationUpdate_Landroid_animation_ValueAnimator_(IntPtr jnienv, IntPtr native__this, IntPtr native_animation)
at (wrapper dynamic-method) System.Object:4634ef59-1681-427d-942e-9589247b8c29 (intptr,intptr,intptr)

**Comment by jamesmontemagno** [comment]
I would open a new issue. Seems like this is a bit deeper in the animation system, are you doing something to it?

**Comment by SlavaChernikoff** [comment]
I created a new issue :)
