### ISSUE TITLE
PullToRefresh  It is always being activated .

### ISSUE THREAD

**Issue by elyfran** [jamesmontemagno/Xamarin.Forms-Awesome-Controls#16]
Hi,
How are u?

I am using the pullto refresh plugin and I have a problem . I used a list and every movement that held down the pull is being activated. how can I solve this?

**Comment by jamesmontemagno** [comment]
Please see sample as it will show you how to implement it as I have had no issues, without any code I can't really help you debug anything.

**Comment by jamesmontemagno** [comment]
All further discussion is here: https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout
