### ISSUE TITLE
Elevation

### ISSUE THREAD

**Issue by juliengloria** [jamesmontemagno/Xamarin.Forms-Awesome-Controls#17]
Hi,
Thanks for your work ! I'd like to use Elevation, to have a shadow like android app.
Could you help me please ?

**Comment by jamesmontemagno** [comment]
I am not sure what you are asking or looking for can you be more specific?

**Comment by juliengloria** [comment]
I try to add shadows around the cardview like this : http://4.bp.blogspot.com/-CChozEvSDf4/VE-TbEiyzbI/AAAAAAAADvg/hnq3aDWBLeY/s1600/Screenshot_2014-10-28-16-22-50.png

**Comment by jamesmontemagno** [comment]
Are you using Xamarin.Forms? You can use the Frame control which is a
cardview and has shadows on iOS too.

James

On Fri, Feb 26, 2016 at 9:47 AM, ac3ju notifications@github.com wrote:

> I try to add shadows around the cardview like this :
> http://4.bp.blogspot.com/-CChozEvSDf4/VE-TbEiyzbI/AAAAAAAADvg/hnq3aDWBLeY/s1600/Screenshot_2014-10-28-16-22-50.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jamesmontemagno/Xamarin.Forms-Awesome-Controls/issues/17#issuecomment-189389257
> .

## 

James Montemagno
http://www.montemagno.com
@jamesmontemagno http://www.twitter.com/jamesmontemagno

**Comment by juliengloria** [comment]
It seems that Android Frame doesn't have shadows :(
