### ISSUE TITLE
PullToRefresh crashes on Android

### ISSUE THREAD

**Issue by SlavaChernikoff** [jamesmontemagno/Xamarin.Forms-Awesome-Controls#19]
We see a lot of crashes in our app using Xamarin Insight.

Stacktrace:

System.ObjectDisposedExceptionCannot access a disposed object. Object name: 'Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer'.
Raw
Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self)
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(string encodedMember, IJavaPeerable self, JniArgumentValue\* parameters)
Android.Views.View.set_Alpha(float value)
Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateOpacity()
Xamarin.Forms.Platform.Android.VisualElementTracker.HandlePropertyChanged(object sender, PropertyChangedEventArgs e)
Xamarin.Forms.Platform.Android.VisualElementTracker.HandleRedrawNeeded(object sender, EventArg<> e)
System.EventHandler>.invoke_void_object_TEventArgs(object, EventArg)(wrapper delegate-invoke)
Xamarin.Forms.VisualElement.BatchCommit()
Xamarin.Forms.AnimationExtensions.HandleTweenerUpdated(object o, EventArgs args)
Xamarin.Forms.Tweener.b__26_0(long step)
Xamarin.Forms.Ticker.SendSignals(int timestep)
at Xamarin.Forms.Platform.Android.AndroidTicker.<.ctor>b__1_0 (System.Object sender, Android.Animation.AnimatorUpdateEventArgs e) <0x65593b18 + 0x0001f> in :0
Android.Animation.ValueAnimator.IAnimatorUpdateListenerImplementor.OnAnimationUpdate(ValueAnimator animation)
Android.Animation.ValueAnimator.IAnimatorUpdateListenerInvoker.n_OnAnimationUpdate_Landroid_animation_ValueAnimator(IntPtr jnienv, IntPtr native__this, IntPtr native_animation)
at (wrapper dynamic-method) System.Object:4634ef59-1681-427d-942e-9589247b8c29 (intptr,intptr,intptr)

**Comment by SlavaChernikoff** [comment]
There are no special animation logic

**Comment by jamesmontemagno** [comment]
Can you add your code. Also if posting a stack trace please use Gist for that.

**Comment by SlavaChernikoff** [comment]
In general we can't even locilize this issue. Just get a lot of errors in out Xamarin Insights.

Thanx!

**Comment by jamesmontemagno** [comment]
If you can create a repo for me I can take a look. I monitor this repo: https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout

which has the latest versions in it. I will close this for now, but feel free to open another issue there.

**Comment by SlavaChernikoff** [comment]
OK James, thank you anyway :) Will try to detect the issue

**Comment by CharlinAgramonte** [comment]
Any news about this issue? I'm having the same problem @SlavaChernikoff @jamesmontemagno

**Comment by corentinaltepe** [comment]
Hi, was the issue fixed ? I'm experiencing the same issue and can't trace back to the origin of the problem.

**Comment by divyachristian** [comment]
any update on this issue? i am facing same problem.but not always.randomly sometimes i get this exception

**Comment by conradh** [comment]
I see this bug now as well... did not have this before. latest build of xamarin.forms 2.5, and pulltorefresh 2.2.1
