### ISSUE TITLE
CardView can't show StackLayout

### ISSUE THREAD

**Issue by petrce** [jamesmontemagno/Xamarin.Forms-Awesome-Controls#2]
Works fine with single Label or if I put same StackLayout before it (but then this same StackLayout outside CardView is never shown).
But when I insert StackLayout with some Labels into it it just show empty CardView.
I am quite sure that there is something wrong with the renderer I just can't find out what is it.
I think that there should be some force redraw called on Content of CardView? 
I am completely stuck do you have any idea please?

**Comment by jamesmontemagno** [comment]
I wasn't able to finish it completely and haven't looked back into it.
