### ISSUE TITLE
Purpose of IsPullToRefreshEnabledProperty?

### ISSUE THREAD

**Issue by JunkyXL86** [jamesmontemagno/Xamarin.Forms-Awesome-Controls#20]
Setting IsPullToRefreshEnabledProperty to false seems to not affect anything. You can still pull the refresher down. I was expecting to happen nothing when you try to pull down. 
Also the refresher appears even when there is no RefreshCommand set. That makes imo no sense, as it does nothing but showing an animating icon.

**Comment by jamesmontemagno** [comment]
This is moved to: https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout
