### ISSUE TITLE
iOS issue with Forms 1.5.0.6446

### ISSUE THREAD

**Issue by philippd** [jamesmontemagno/Xamarin.Forms-Awesome-Controls#6]
Thanks a lot for this layout! It does exactly what I was looking for.

Unfortunately after testing it with Xamarin Forms 1.5.0.6446 there now is a strange rendering issue on iOS: The content of the PullToRefreshLayout is visible in the background when pulled down.

Screenshot:

![ios-refresh-bug](https://cloud.githubusercontent.com/assets/684943/9886335/03b4459e-5bea-11e5-9ec5-ec2131408d65.png)

Do you have any idea how this could be fixed in the iOS renderer?

I pushed a version of your project with the unstable forms version here: https://github.com/philippd/Xamarin.Forms-Awesome-Controls

**Comment by philippd** [comment]
I updated the isse because the same thing happens in the stable release 1.5.0.6446

**Comment by eiriklie** [comment]
I'm seeing the same behaviour. Only tried the component it with stable release 1.5.0.6446.

![screen-shot-2015-09-24-at-09 38](https://cloud.githubusercontent.com/assets/11404585/10067934/ad34d7e8-62a0-11e5-8f11-5deecb34e95c.jpg)

**Comment by philippd** [comment]
@eli-ums If you set the BackgroundColor of the PullToRefreshLayout it will work just fine

**Comment by eiriklie** [comment]
Thanx a lot! that did the trick, and saved me a couple of hours of frustration :)

**Comment by jamesmontemagno** [comment]
Updated in latest package.

**Comment by jamesmontemagno** [comment]
I didn't change the default background to white though, seems like you can set that manually.
