### ISSUE TITLE
Issue with smaller content size

### ISSUE THREAD

**Issue by HaiderAbbas** [jamesmontemagno/Xamarin.Forms-Awesome-Controls#8]
For iOS, it works fine only when the content size inside the pull refresh layout is bigger than the pull refresh layout's size. I tested the sample available on GitHub (scrollview XAML) with fewer boxes/items inside the scroll view e.g. 2. Now when I try to pull the list down, nothing happens.

**Comment by HaiderAbbas** [comment]
I have fixed this issue. Can you please merge that change or allow me to commit/push my change in this repository. Here is the change I mage after doing the Fork:
https://github.com/HaiderAbbas/Xamarin.Forms-Awesome-Controls/commit/8789b71a5845c8a8b5967d9f80c6c8b478479291

**Comment by jamesmontemagno** [comment]
PUlled in and pushing an update
